channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - geopandas
  - pandas
  - pygmt
# don't fuss about versions for now,
# but here are the version numbers from AaronT's personal computer
#matplotlib==3.5.1
#numpy==1.21.5
#pandas=1.4.3
#pygmt=v0.5.0
